# Site settings
title: cPanel Paper Lantern Example Customizations
email: devnull@cpanel.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "Paper_Lantern_Customizations" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
